// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/state.ts";
import * as $$$1 from "./loaders/image.ts";
import * as $$$2 from "./loaders/redirectsFromCsv.ts";
import * as $$$3 from "./loaders/secret.ts";
import * as $$$4 from "./loaders/font.ts";
import * as $$$$0 from "./handlers/router.ts";
import * as $$$$1 from "./handlers/sitemap.ts";
import * as $$$$2 from "./handlers/proxy.ts";
import * as $$$$3 from "./handlers/fresh.ts";
import * as $$$$4 from "./handlers/redirect.ts";
import * as $$$$$0 from "./pages/LivePage.tsx";
import * as $$$$$$0 from "./sections/UseSlot.tsx";
import * as $$$$$$1 from "./sections/Slot.tsx";
import * as $$$$$$2 from "./sections/SEO.tsx";
import * as $$$$$$3 from "./sections/EmptySection.tsx";
import * as $$$$$$4 from "./sections/PageInclude.tsx";
import * as $$$$$$5 from "./sections/SEOPLP.tsx";
import * as $$$$$$6 from "./sections/Analytics.tsx";
import * as $$$$$$7 from "./sections/SEOPDP.tsx";
import * as $$$$$$$0 from "./matchers/date.ts";
import * as $$$$$$$1 from "./matchers/environment.ts";
import * as $$$$$$$2 from "./matchers/site.ts";
import * as $$$$$$$3 from "./matchers/location.ts";
import * as $$$$$$$4 from "./matchers/random.ts";
import * as $$$$$$$5 from "./matchers/multi.ts";
import * as $$$$$$$6 from "./matchers/cron.ts";
import * as $$$$$$$7 from "./matchers/device.ts";
import * as $$$$$$$8 from "./matchers/host.ts";
import * as $$$$$$$9 from "./matchers/always.ts";
import * as $$$$$$$10 from "./matchers/userAgent.ts";
import * as $$$$$$$$0 from "./flags/audience.ts";
import * as $$$$$$$$1 from "./flags/multivariate.ts";
import * as $$$$$$$$2 from "./flags/everyone.ts";
import * as $$$$$$$$3 from "./flags/flag.ts";
import * as $$$$$$$$$0 from "./actions/secrets/encrypt.ts";
import { AppManifest } from "$live/types.ts";

const manifest = {
  "loaders": {
    "site/loaders/font.ts": $$$4,
    "site/loaders/image.ts": $$$1,
    "site/loaders/redirectsFromCsv.ts": $$$2,
    "site/loaders/secret.ts": $$$3,
    "site/loaders/state.ts": $$$0,
  },
  "handlers": {
    "site/handlers/fresh.ts": $$$$3,
    "site/handlers/proxy.ts": $$$$2,
    "site/handlers/redirect.ts": $$$$4,
    "site/handlers/router.ts": $$$$0,
    "site/handlers/sitemap.ts": $$$$1,
  },
  "pages": {
    "site/pages/LivePage.tsx": $$$$$0,
  },
  "sections": {
    "site/sections/Analytics.tsx": $$$$$$6,
    "site/sections/EmptySection.tsx": $$$$$$3,
    "site/sections/PageInclude.tsx": $$$$$$4,
    "site/sections/SEO.tsx": $$$$$$2,
    "site/sections/SEOPDP.tsx": $$$$$$7,
    "site/sections/SEOPLP.tsx": $$$$$$5,
    "site/sections/Slot.tsx": $$$$$$1,
    "site/sections/UseSlot.tsx": $$$$$$0,
  },
  "matchers": {
    "site/matchers/always.ts": $$$$$$$9,
    "site/matchers/cron.ts": $$$$$$$6,
    "site/matchers/date.ts": $$$$$$$0,
    "site/matchers/device.ts": $$$$$$$7,
    "site/matchers/environment.ts": $$$$$$$1,
    "site/matchers/host.ts": $$$$$$$8,
    "site/matchers/location.ts": $$$$$$$3,
    "site/matchers/multi.ts": $$$$$$$5,
    "site/matchers/random.ts": $$$$$$$4,
    "site/matchers/site.ts": $$$$$$$2,
    "site/matchers/userAgent.ts": $$$$$$$10,
  },
  "flags": {
    "site/flags/audience.ts": $$$$$$$$0,
    "site/flags/everyone.ts": $$$$$$$$2,
    "site/flags/flag.ts": $$$$$$$$3,
    "site/flags/multivariate.ts": $$$$$$$$1,
  },
  "actions": {
    "site/actions/secrets/encrypt.ts": $$$$$$$$$0,
  },
};

export type Manifest = typeof manifest;

export const name = "site";

export default manifest satisfies AppManifest;
