import { State } from "./state.ts";
export type { State };
import { App, AppContext as AC } from "../deps.ts";
// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/bin.ts";

const manifest = {
  "loaders": {
    "mcandeia/bins/loaders/bin.ts": $$$0,
  },
};

export type Manifest = typeof manifest;

export const name = "mcandeia/bins";

export default function App(
  state: State,
): App<Manifest, State> {
  return {
    manifest,
    state,
  };
}

export type AppContext = AC<ReturnType<typeof App>>;
