// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$0 from "./handlers/router.ts";
import * as $$$$1 from "./handlers/redirect.ts";
import { AppManifest } from "$live/types.ts";

const manifest = {
  "handlers": {
    "deco/handlers/redirect.ts": $$$$1,
    "deco/handlers/router.ts": $$$$0,
  },
};

export type Manifest = typeof manifest;

export const name = "deco";

export default manifest satisfies AppManifest;
